version: '3.8'

services:
  dockermanager:
    image: aszer0s/dockermanager:latest
    container_name: dockermanager
    ports:
      - "9090:9090"
    volumes:
      - ./data:/app
    environment:
      - GIN_MODE=release
    restart: unless-stopped
